# Generated by Django 4.0.4 on 2022-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows', models.IntegerField()),
                ('iphone', models.IntegerField()),
                ('mac', models.IntegerField()),
                ('android', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
    ]
